name: face_recognization
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  #agora
  agora_rtc_engine: ^6.3.2
  #permissions
  permission_handler: ^11.3.1
  #reaction button
  flutter_reaction_button: ^3.0.0+3
  #bio metrics
  google_ml_kit: ^0.19.0
  google_mlkit_face_detection: ^0.12.0
  #image
  image_picker: ^1.1.2
  camera: ^0.11.0+2
  #path
  path_provider: ^2.1.5
  lottie: ^3.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/animations/
  #   - images/a_dot_ham.jpeg
